# ##########################################################
# 
# Title			: bd_script_changer.py
# Author 		: O.C.
# Description	: Applies a few changes to the tcl script 
#				  generated by the "write_bd_tcl"
#				  function
# 
# ##########################################################

#Important to get current path and to delete temp files
import inspect, os, sys

#Getting the current path of this file
current_path = os.path.dirname(os.path.abspath(os.path.basename(__file__)))

#Getting the names of every file within the <project>/src/bd folder
bd_files = []
for subdir, dirs, files in os.walk(current_path):
    for file in files:
		#We take only the .tcl files that are different from the block_design_tcl.tcl
        if file.find(".tcl")!= -1 and file != "block_design_tcl.tcl" :
            bd_files.append(file)

#Changing every block design tcl file in the directory
for filename in bd_files :	
	
	#Setting a flag since we change only the first occurence
	initial = 0
	
	#We open a temporary file to store the new information in it
	with open("tmp.tcl","w+") as tmp :
		
		#Opens up the tcl script
		with open(filename, "r+") as f:
		
			#starting from the beginning of the file
			f.seek(0)
			
			for line in f:
			
				#Strips the line of the line changing function
				line = line.rstrip("\n")
				
				#Changes the path 
				var1 = "set origin_dir"
				if line.find(var1)!= -1 and initial == 0 :
					line = "	set origin_dir "+ current_path  + "\..\..\IP_repo"
					line = line.replace('\\','/') #there are errors otherwise
					initial = 1
						
				#Prints the new lines in a temporary file
				tmp.write(line+"\n")
		
		#Going back to the beginning of the temp file
		tmp.seek(0)		
		
		#Rebuilding the original file using the temporary file
		for line in tmp :
			with open(filename,"w") as f:
			
				#Going to the beginning of the original file
				f.seek(0)
				for line in tmp :					
					f.write(line)
	#Removing the temporary file
	os.remove("tmp.tcl")


	
